In [1]:
import numpy as np

arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[8]  ## The value in a certain index [index]

8

In [3]:
arr[:5]

array([0, 1, 2, 3, 4])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5]=100  ## assigning a value to a certain index
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr[0:5]=[1,2,3,4,5]
arr

array([ 1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10])

In [16]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
SliceA=arr[0:5]
SliceA

array([0, 1, 2, 3, 4])

In [19]:
SliceA[:]=99 ## Assigning a value to all the elements of the array
SliceA

array([99, 99, 99, 99, 99])

In [20]:
arr  ## The main elements are affected

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arrc=arr.copy() ## Take a copy of the array
arrc

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr2=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr2[0][1]

10

In [67]:
arr2[:2,1:]

array([[10, 15],
       [25, 30]])