In [1]:
import numpy as np

In [2]:
lis=[1,2,3]
lis

[1, 2, 3]

In [3]:
np.array(lis)

array([1, 2, 3])

In [5]:
lis2=[[1,2,3],[4,5,6],[7,8,9]]
lis2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(lis2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr=np.arange(5) # Make an array of 5 elements
arr

array([0, 1, 2, 3, 4])

In [12]:
arr2=np.arange(2,10,2)   ## arange(start,end,step)
arr2

array([2, 4, 6, 8])

In [17]:
zeros=np.zeros(5) ## Make a vector of zeros
zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
zeros2=np.zeros((5,5))  # Make a 5*5 matrix (rows,coloumns)
zeros2

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [22]:
ones=np.ones((5,5)) # Make a mtrix of ones
ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
identity=np.eye(4)  # Make an identity matrix 4*4
identity

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
ln=np.linspace(0,10,10)  # Divide the range between 0 and 10  with 10 pieces  (Start,End,El Ta2sema)
ln

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [29]:
randomarr=np.random.rand(2)  # Generating 2 random numbers between 0 & 1
randomarr

array([ 0.41026732,  0.29758135])

In [30]:
randomarr2=np.random.rand(5,5)  # Generating a 5*5 random matrix ** don't need to add the size in a tubile
randomarr2

array([[ 0.75257174,  0.63080565,  0.3911706 ,  0.85509218,  0.35761001],
       [ 0.03524299,  0.65231339,  0.8003378 ,  0.38360908,  0.03175312],
       [ 0.18402608,  0.63451624,  0.7680093 ,  0.18121182,  0.70916942],
       [ 0.58769765,  0.49830799,  0.56345337,  0.19232291,  0.23721586],
       [ 0.89503354,  0.52194032,  0.48477849,  0.962571  ,  0.20593274]])

In [32]:
randomarr3=np.random.randn(5,5)  # Generating 5*5 gaussian random matrix ** no limits for the generated numbers
randomarr3

array([[ 1.15528915, -2.2388765 , -0.30574409,  0.08860104,  1.04786584],
       [ 0.39419423, -0.59600459,  0.17691183,  0.78746476, -0.71068658],
       [ 0.12187537,  1.00095955,  2.05205383,  1.8755605 , -3.35905661],
       [ 0.86182941,  1.45362508,  1.24591378, -1.14731827,  0.62607648],
       [-0.75929368,  1.12164865,  0.61364856,  1.12582257,  0.39089696]])

In [33]:
randomarr4=np.random.randint(0,50,10)  # Generating vector of 10 integers from 0 to 50 
randomarr4

array([ 2, 27, 44, 24,  0, 35, 48, 40, 23,  5])

In [35]:
randomarr4.reshape(5,2) # Reshape the array ento 5*2 matrixarr

array([[ 2, 27],
       [44, 24],
       [ 0, 35],
       [48, 40],
       [23,  5]])

In [40]:
randomarr4.max() ## Get the maximum number of an array

48

In [37]:
randomarr4.argmax() ## Get the location of the maximum

6

In [38]:
randomarr4.min() ## Get the minimum number of an array

0

In [39]:
randomarr4.argmin() ## Get the location of the minimum

4

In [46]:
randomarr4.reshape(1,10)  ## reshape the matrix to a row matrix

array([[ 2, 27, 44, 24,  0, 35, 48, 40, 23,  5]])

In [47]:
randomarr4.shape

(10,)

In [43]:
randomarr4.reshape(10,1)  ## reshape the matrix to a coloumn matrix

array([[ 2],
       [27],
       [44],
       [24],
       [ 0],
       [35],
       [48],
       [40],
       [23],
       [ 5]])

In [45]:
randomarr4.shape

(10,)

In [48]:
x=randomarr4.reshape(1,10)
x.shape

(1, 10)